python main.py \
--dataroot /home/yifanc3/dataset/building_data/128_0over_whole/ \
--date 20building_aug \
--loss wbce \
--model unet \
--ckpt_name unet112_wbce7_lr6_whole0over \
--num_filters 112 \
--input_channel 1 \
--n_epoch 100 \
--dim 128 \
--batch_size 16 \
--frame_name DEM_retile/ \
--mask_name labels_retile/ \
--visualize